name: "Generate Documentation"
on:
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: '3.x'
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: python -m pip install -r docsrc/requirements.txt
        build-command: "sphinx-build -b html ../docsrc/ _build -w /tmp/sphinx.log "
        docs-folder: "docs/"
    - run: pip list
