name: "Generate Documentation"
on:
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build -b html docsrc/ _build -f /tmp/sphinx.log "
        docs-folder: "docs/"