name: "Generate Documentation"
on:
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'
    - run: pip3 install -r docsrc/requirements.txt
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build -b html ../docsrc/ _build -w /tmp/sphinx.log "
        docs-folder: "docs/"