name: "Generate Documentation"
on:
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: py-actions/py-dependency-install@v3
      with:
        path: "docsrc/requirements.txt"
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build -b html ../docsrc/ _build -w /tmp/sphinx.log "
        docs-folder: "docs/"