name: "Generate Documentation"
on:
  push:
    branches:
      - beta
      - test

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: '3.x'
    - name: Generate Documentation
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: python -m pip install -r docsrc/requirements.txt
        build-command: "sphinx-build -b html ../docsrc/ _build -w /tmp/sphinx.log"
        docs-folder: "docsrc/"
    - name: Move HTML
      run: rsync -avzh docsrc/_build/* docs/
    - name: Update Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        add-paths: docs/*
        delete-branch: false
        title: Documentation Update
        labels: documentation, python, polaris
    - name: Check outputs
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"