-name: Run Tests
on:
  push:
    branches:
      - master
      - beta
  pull_request:
    branches:
      - '**'


name: Run Tests
  jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [uuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8']
    name: python ${{ matrix.python-version }} - ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
    - name: Initialize python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install CI dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint mypy
      - name: install SDK
        run: python setup.py install
      - name: lint - pylint
        # Disabled linters:
        # R0801 - duplicate-code
        # R0913 - too-many-arguments
        # R0914 - too-many-locals
        # C0103 - invalid-name
        # C0114 - missing-module-docstring
        # C0116 - missing-function-docstring
        # C0209 - consider-using-f-string
        # C0301 - line-too-long
        # C0302 - too-many-lines
        # C0415 - import-outside-toplevel
        # W0212 - protected-access
        # C0115 - missing-class-docstring
        # C0201 - consider-iterating-dictionary
        # C0206 - consider-using-dict-items
        # C0304 - missing-final-newline
        # C0305 - trailing-newlines
        # C0411 - wrong-import-order
        # C0413 - wrong-import-position
        # C0414 - useless-import-alias
        # E0102 - function-redefined
        # E0401 - import-error
        # E0611 - no-name-in-module
        # E1101 - no-member
        # R0902 - too-many-instance-attributes
        # R0912 - too-many-branches
        # R0915 - too-many-statements
        # R0916 - too-many-boolean-expressions
        # R1702 - too-many-nested-blocks
        # R1710 - inconsistent-return-statement
        # R1720 - no-else-raise
        # R1732 - consider-using-with
        # W0102 - dangerous-default-value
        # W0105 - pointless-string-statement
        # W0107 - unnecessary-pass
        # W0404 - reimported
        # W0511 - fixme
        # W0611 - unused-import
        # W0612 - unused-variable
        # W0613 - unused-argument
        # W0621 - redefined-outer-name
        # W0622 - redefined-builtin
        # W0702 - bare-except
        # W0703 - broad-except
        # W0706 - try-except-raise
        # W0707 - raise-missing-from
        # W1510 - subprocess-run-check
        # W1514 - unspecified-encoding
        run: |
          python -m pylint $(git ls-files '*.py') \
            -d R0801 \
            -d R0913 \
            -d R0914 \
            -d C0103 \
            -d C0114 \
            -d C0116 \
            -d C0209 \
            -d C0301 \
            -d C0302 \
            -d C0415 \
            -d W0212 \
            -d C0115 \
            -d C0201 \
            -d C0206 \
            -d C0304 \
            -d C0305 \
            -d C0411 \
            -d C0413 \
            -d C0414 \
            -d E0102 \
            -d E0401 \
            -d E0611 \
            -d E1101 \
            -d E4702 \
            -d R0902 \
            -d R0912 \
            -d R0915 \
            -d R0916 \
            -d R1702 \
            -d R1710 \
            -d R1720 \
            -d R1732 \
            -d W0102 \
            -d W0105 \
            -d W0107 \
            -d W0404 \
            -d W0511 \
            -d W0611 \
            -d W0612 \
            -d W0613 \
            -d W0621 \
            -d W0622 \
            -d W0702 \
            -d W0703 \
            -d W0706 \
            -d W0707 \
            -d W1510 \
            -d W1514
        shell: bash
      - name: lint - mypy
        run: python -m mypy --strict $(git ls-files '*.py') || true
      - name: unit tests
        run: |
          pip install -r tests/requirements.txt
          pytest tests/rubrik_polaris
